apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: academic-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: academic-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: academic-backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
